# .air.toml
root = "."
tmp_dir = "tmp"

[build]
  bin = "tmp/main"
  cmd = "go build -o ./tmp/main ."
  include_ext = ["go", "tpl", "tmpl", "html"]
  exclude_dir = ["assets", "tmp", "vendor"]
  log = "air.log"

[log]
  time = true

[serve]
  cmd = "./tmp/main"
  delay = 1000
  kill_delay = 500
~̀